### ISSUE TITLE
Update KPCO consent+HIPAA forms for PI change (October release)

### ISSUE THREAD

**Issue by kmazzilli** [episphere/connect#1132]
As part of the October release, we need to update the KPCO English and Spanish consent and HIPAA forms in the PWA and SMDB to reflect their change in PI. This is only being updated for KPCO in English and Spanish, no other sites.

**Consent (English)**
 Finalized Form Box Link: https://nih.app.box.com/file/1670686268476)
Link Tracked Version for HTML: https://nih.app.box.com/file/1648731498702
Variable Response Label: KPCO_Consent_V0.04

**Consent (Spanish)**
 Finalized Form Box Link: https://nih.app.box.com/file/1670693494908
Link Tracked Version for HTML: https://nih.app.box.com/file/1648724176009
Variable Response Label: KPCO_Consent_V0.04_Span

**HIPAA (English)**
Finalized Form Box Link: https://nih.app.box.com/file/1666837883854 
Link Tracked Version for HTML: https://nih.app.box.com/file/1648728712782 
Variable Response Label: KPCO_HIPAA_V0.03

**HIPAA (Spanish)**
 Finalized Form Box Link: https://nih.app.box.com/file/1666845909170
 Link Tracked Version for HTML: https://nih.app.box.com/file/1648729931207
 Variable Response Label: KPCO_HIPAA_V0.03_Span

This should be updated the same we have for past consent updates where the consent and HIPAA version that is displayed will be tied to the date the participant consented. New participants will receive the updated forms, while old participants will receive the old forms they signed under.

PWA: The revised consent+HIPAA should be updated in the PWA in the following places for recruits who sign the consent on and after time of prod push: (1) HTML consent form preview box on pg 9 of eConsent, (2) downloadable unsigned consent form on pg9 eConsent, (3) downloadable signed consent form on next screen after signing, (4) downloadable signed consent form on ‘Forms’ tab

SMDB: The revised consent+HIPAA should be updated in the SMDB in the following places for recruits who sign the consent on and after time of prod push:(1) Add consent and HIPAA forms to SMDB downloadable rows on Participant Summary page, (2) 'consent version' and 'HIPAA version' variable bubble fields at pt summary page

**Comment by kmazzilli** [comment]
I updated the issue with the consent form links now that this has received IRB approval!

**Comment by robertsamm** [comment]
Hi @bransteitterbr is this one ready to test or still in PR? I thought on the punch list call yesterday I heard this was in dev and ready for testing, but I could def have misheard!

I just logged into the dev PWA in incognito mode as a new KPCO recruit and the box display for both the Consent and HIPAA are giving a 404 error and the downloadable forms are still showing the old versions with Heather as the PI.

**Comment by bransteitterbr** [comment]
Hi @robertsamm I forgot to advance the form versions to use the new html and pdfs.  Sorry I only tested existing downloads and not new participants.  I will have a fix out shortly so you can test.

**Comment by bransteitterbr** [comment]
@robertsamm The fix has been merged to dev so you can test this

**Comment by robertsamm** [comment]
Good morning @bransteitterbr, I just tried again this morning with a new account after clearing my cache and unfortunately am still getting the same error for the Box display and the downloaded forms are still the old version.

![image](https://github.com/user-attachments/assets/ed3aea25-c853-4af6-8e2e-92f3ce0b267e)
![image](https://github.com/user-attachments/assets/20d5f1ac-4258-488b-a51a-a6c2dcf93f0a)

**Comment by robertsamm** [comment]
Hi @bransteitterbr just wanted to check in on this one, can you let me know when this is ready to test in dev?

**Comment by robertsamm** [comment]
Hi @bransteitterbr I found two small issues with the dates in the HTML box display for two of the forms. See below.

1. English HIPAA - need to change version date from '16/09/2024' to '09/16/2024'
![image](https://github.com/user-attachments/assets/491463dd-3ddf-491e-8549-dd8d61462750)

3. Spanish consent - need to change version date from '16/09/2024' to '09/16/2024' (I recognize that this is the proper display of a version date but it does not match the NIH approved PDF of the consent. Will discuss with Ops team whether we want to fix the Spanish dates in a future release but for now need to align with the approved version)
![image](https://github.com/user-attachments/assets/aa8964a7-1341-4baf-b000-a62a9253a0ae)

The English Consent and Spanish HIPAA looked good, no changes needed there.

**Comment by bransteitterbr** [comment]
@robertsamm  The date change has been updated and should be deployed shortly

**Comment by robertsamm** [comment]
Thanks @bransteitterbr for the quick fix, this looks good! Ready for stage.

**Comment by robertsamm** [comment]
Hi @bransteitterbr the KPCO team caught an issue during stage testing that I missed in dev. In the HTML box display of both the English and Spanish versions of both the consent and HIPAA forms (all versions of the forms for the HTML display), Larissa's credentials after her name are missing the 'MPH' credential.

It should state: Larissa White, PhD, MPH, CPH

![image](https://github.com/user-attachments/assets/599fbb0f-ec27-425c-9883-be6592d77d09)
![image](https://github.com/user-attachments/assets/06fc87e8-3712-499d-86a2-90b93a00f326)
I didn't take a screenshot of the Spanish forms, but it needs updating there as well.

Are you able to fix this in both dev and stage?

**Comment by bransteitterbr** [comment]
@robertsamm This is ready for testing again

**Comment by robertsamm** [comment]
Thanks @bransteitterbr this is retested in both dev and stage and look good! Ready for prod. Thanks for the quick fix! I'll also let the KPCO team that the issue was fixed.
