### ISSUE TITLE
KPCO Baseline collection entered as Follow-up 1 collection (Biospecimens)

### ISSUE THREAD

**Issue by erincschwartz** [episphere/connect#1193]
The Baseline collection for Connect ID 8161066636 was somehow entered into the Biospecimen Dashboard as a Follow-up 1 collection.  

**Please check Prod dashboard functionality to determine whether selection of any other visit besides Baseline is permitted** (all follow-up options should be disabled)

**Comment by sonyekere** [comment]
Hi @erincschwartz We're you able to check the QC data? Has this been resolved?

**Comment by sonyekere** [comment]
This issue has been fixed in prod, but will keep the issue open to further monitor.

**Comment by erincschwartz** [comment]
In the Biospecimen Prod file from 2/3/2025, it still shows the visit as Follow-up 1, however, in the SMDB the Baseline blood and urine are now showing as collected. 

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/6fceda13-6078-4929-bba3-923ca762ca20" />

**Comment by KELSEYDOWLING7** [comment]
BioSpm_Visit_v1r0 is the first nested variable for most of the biospecimen variables in the participants table. It comes in automatically (concept ID 331584571)

![Image](https://github.com/user-attachments/assets/d95a5fbc-c7d8-4cf1-9164-b7e703bfbf18)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 for the Connect ID in question, somehow - we don't know how- the data for this ppt got nested under followup1 as opposed to baseline. 

we did a prod manual change to fix the data for this person so I should now be nested under baseline. Yet in the prod biospec file, this variable is still appearing as follow-up 1. 

can you look at the data and determine why this is? did we miss something in the manual change?

**Comment by KELSEYDOWLING7** [comment]
From what I can see, the issue is that the data in the follow up variables were not deleted. We can tell this because they have data in variables with the nested value 496823485, meaning follow up, AS WELL AS variables with the nested value  of 266600170 for baseline.
- Data in both d_130371375_d_496823485_d_222373868 and d_130371375_d_266600170_d_222373868
- Data in both d_130371375_d_496823485_d_648228701 and d_130371375_d_266600170_d_648228701,
- Data in both d_130371375_d_496823485_d_648936790 and d_130371375_d_266600170_d_648936790, 
- Data in both d_130371375_d_496823485_d_731498909 and d_130371375_d_266600170_d_731498909

In some cases the values are the same for baseline and follow up, in other cases they're different. But I would think all the data under follow up needs to be deleted

**Comment by brotzmanmj** [comment]
@anthonypetersen  can you confirm if this is what you see, and if so we can put this on this weeks prod manual change log?

**Comment by anthonypetersen** [comment]
The data structure @KELSEYDOWLING7 is referencing is for incentives and they are default variables

**Comment by erincschwartz** [comment]
@anthonypetersen You are correct, this was not included in the Prod manual change request. The way this variable is presented in the Biospecimen Variable Structure document led me to believe this was just for Research collections.

<img width="316" alt="Image" src="https://github.com/user-attachments/assets/30303631-71af-4781-97ed-ae6155fff057" />

@mnataraj92 please add this change to the Prod Manual Change log---331584571 needs to be updated to 266600170 

Also, we have no visibility into payment round data outside of Baseline. @KELSEYDOWLING7 please check if any other participants have payment round data under any of the other rounds that are not Baseline outside of this participant?

**Comment by KELSEYDOWLING7** [comment]
Please disregard my comment on the incentive variables, it seems that all consented participants have those follow up incentive variables automatically flagged as no. This person also has those flags as no. Apologies for the confusion, I have not worked with these variables hardly ever.

All 16 variables in the participants table with 496823485 nested for follow up are NO (if a flag) or NULL (if a timestamp/setting/ect.) as expected.

Fortunately, the biospecimen table shows that this is the only person with d_331584571=496823485 (BioSpm_Visit_v1r0=follow up 1)

**Comment by mnataraj92** [comment]
> [@anthonypetersen](https://github.com/anthonypetersen) You are correct, this was not included in the Prod manual change request. The way this variable is presented in the Biospecimen Variable Structure document led me to believe this was just for Research collections.
> 
> <img alt="Image" width="316" src="https://private-user-images.githubusercontent.com/157617486/410181753-30303631-71af-4781-97ed-ae6155fff057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NTI5MjAsIm5iZiI6MTczODg1MjYyMCwicGF0aCI6Ii8xNTc2MTc0ODYvNDEwMTgxNzUzLTMwMzAzNjMxLTcxYWYtNDc4MS05N2VkLWFlNjE1NWZmZjA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNlQxNDM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGVmN2ZlZTk1ZGJhN2NjYTI1ZWY0NjkyMzQ3Nzk3ZDdkNGQ3ZDg3YjU3ZGVlMDliZjUwY2FjMzYzNTc2N2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VFOcath-wVeEWdA2DHLHyukzNv9OU8aRWYDgyy99QlU">
> [@mnataraj92](https://github.com/mnataraj92) please add this change to the Prod Manual Change log---331584571 needs to be updated to 266600170
> 
> Also, we have no visibility into payment round data outside of Baseline. [@KELSEYDOWLING7](https://github.com/KELSEYDOWLING7) please check if any other participants have payment round data under any of the other rounds that are not Baseline outside of this participant?

I have added this to the prod change log

**Comment by mnataraj92** [comment]
This change has been made in prod.

**Comment by erincschwartz** [comment]
Checked prod data, BioSpm_Visit_v1r0 is now set to Baseline. 

One last variable needs to be updated, <254109640> SMMet_BLSamplesColl_v1r0  is still null, this should be set to Yes, since Baseline blood and urine were collected. @mnataraj92, please add this to the prod change log.

**Comment by mnataraj92** [comment]
This has been added to the prod change log

**Comment by mnataraj92** [comment]
> Checked prod data, BioSpm_Visit_v1r0 is now set to Baseline.
> 
> One last variable needs to be updated, <254109640> SMMet_BLSamplesColl_v1r0 is still null, this should be set to Yes, since Baseline blood and urine were collected. [@mnataraj92](https://github.com/mnataraj92), please add this to the prod change log.

This change has been made in prod
