### ISSUE TITLE
Mixed Data Field Types

### ISSUE THREAD

**Issue by hullingsag** [episphere/connect#1369]
Hi all, 

In an effort to consolidate open issues in the Analyticsphere and help facilitate communication between Analytics & DevOps, we decided to move this issue over to the Connect Development & Support project board. 

As a quick recap: 

There is a recurring issue in Firestore that is causing problems downstream in BigQuery. For example, some data fields in Firestore are showing up as mixed field types with different suffixes (e.g., ".string", ".integer"). The '.provided' field specifies the data type in which the value is given. 

We will want to find all variables in the Connect dataset that have mixed data types and fix them in Firestore before they get to BigQuery. 

Previous issues and related threads: 

-  https://github.com/Analyticsphere/metricsReportsRequests/issues/240

-  https://github.com/episphere/connect/discussions/1262

Assigning Nanci, Warren, and Tony

**Comment by anthonypetersen** [comment]
@hullingsag are there variables that are currently experiencing this issue? we originally had a weekly meeting between Dev Ops and Analytics where issues like this could be reported and resolved, but Analytics determined the meeting was no longer required and would keep Dev Ops informed about when issues arose.

**Comment by anthonypetersen** [comment]
related - https://github.com/episphere/connect/issues/1049

**Comment by anthonypetersen** [comment]
the ones from biospecimen, notifications, and participants are likely easy fixes, the ones from the surveys seem to stem from a bug involving grids from last summer that has been resolved (we will need to determine how to clean the data)

**Comment by hullingsag** [comment]
Hi @anthonypetersen - Sorry for the delay! Here is the updated list of variables and tables for where we're still seeing issues:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hullingsag/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hullingsag/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


value | count | table_name | field_path
-- | -- | -- | --
entity | 19273 | covid19Survey_v1 | D_114280729.provided
string | 243 | covid19Survey_v1 | D_114280729.provided
entity | 8125 | covid19Survey_v1 | D_749956170.provided
string | 131 | covid19Survey_v1 | D_749956170.provided
entity | 53383 | module2_v2 | D_128705365.provided
string | 8 | module2_v2 | D_128705365.provided
entity | 37582 | module3_v1 | D_633553324.provided
string | 58 | module3_v1 | D_633553324.provided
entity | 579 | module4_v1 | D_135529881.provided
string | 50 | module4_v1 | D_135529881.provided
entity | 39 | module4_v1 | D_219317801.provided
string | 3 | module4_v1 | D_219317801.provided
entity | 32409 | module4_v1 | D_440093675.provided
string | 2430 | module4_v1 | D_440093675.provided
entity | 1051 | module4_v1 | D_679430807.provided
string | 83 | module4_v1 | D_679430807.provided
entity | 2214 | module4_v1 | D_786253125.provided
string | 194 | module4_v1 | D_786253125.provided
entity | 17820 | module4_v1 | D_968388901.provided
string | 1325 | module4_v1 | D_968388901.provided
integer | 27 | notifications | errorCode.provided
string | 172953 | notifications | errorCode.provided
integer | 487 | participants | d_837244890.provided
string | 15 | participants | d_837244890.provided



</body>

</html>

I've updated the code to filter out any variables with a 0 count so don't worry about those.

**Comment by we-ai** [comment]
There another case of mixed string and integer types:
- Tier: stage
- Table/Collection: participants
-  Connect ID: 1924364711
- Issue: For concept ID 250235523, instead of an integer value (104430631), a string value ("104430631") was saved
- Action taken: manually changed "104430631" to 104430631 in Firestore
- Todo: check to see whether there's a bug causing this issue

**Comment by hullingsag** [comment]
Updated counts with mixed field type issues: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hullingsag/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hullingsag/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


value | count | table_name | field_path
-- | -- | -- | --
integer | 36373 | biospecimen | d_646899796.provided
string | 2 | biospecimen | d_646899796.provided
integer | 36096 | biospecimen | d_928693120.provided
string | 3 | biospecimen | d_928693120.provided
string | 243 | covid19Survey_v1 | D_114280729.provided
entity | 22380 | covid19Survey_v1 | D_114280729.provided
entity | 9339 | covid19Survey_v1 | D_749956170.provided
string | 131 | covid19Survey_v1 | D_749956170.provided
entity | 59776 | module2_v2 | D_128705365.provided
string | 8 | module2_v2 | D_128705365.provided
NA | 0 | module3_v1 | D_470862706.provided
entity | 41242 | module3_v1 | D_633553324.provided
string | 58 | module3_v1 | D_633553324.provided
entity | 637 | module4_v1 | D_135529881.provided
string | 50 | module4_v1 | D_135529881.provided
entity | 40 | module4_v1 | D_219317801.provided
string | 3 | module4_v1 | D_219317801.provided
entity | 35377 | module4_v1 | D_440093675.provided
string | 2430 | module4_v1 | D_440093675.provided
entity | 1136 | module4_v1 | D_679430807.provided
string | 83 | module4_v1 | D_679430807.provided
entity | 2383 | module4_v1 | D_786253125.provided
string | 194 | module4_v1 | D_786253125.provided
entity | 19750 | module4_v1 | D_968388901.provided
string | 1325 | module4_v1 | D_968388901.provided
string | 193001 | notifications | errorCode.provided
integer | 1330 | notifications | errorCode.provided
NA | 0 | participants | d_569151507.d_250235523.provided
NA | 0 | participants | d_569151507.d_810747471.provided
string | 179 | participants | d_837244890.provided
integer | 9063 | participants | d_837244890.provided
integer | 45477 | promis_v1 | D_101862879.provided
float | 1 | promis_v1 | D_101862879.provided
integer | 45477 | promis_v1 | D_410751656.provided
float | 1 | promis_v1 | D_410751656.provided



</body>

</html>

**Comment by hullingsag** [comment]
**Note for Analytics:** the code for this can be found under 'mixed_field_types.R' in our Analyticsphere Ad Hoc repo (https://github.com/Analyticsphere/ad-hoc)

**Comment by FrogGirl1123** [comment]
@anthonypetersen I would prefer to have Nulls instead of empty strings when someone skips the 'Country of Origin' question.

I'll schedule a quick meeting with you, me and Michelle H., who's going to be making the back-up tables, to go over the survey based issues next week.

**Comment by michellehudson** [comment]
Hi @anthonypetersen @FrogGirl1123 

I have created a dataset on BigQuery - QuestionnaireStringBackup. It contains a table for each survey (4) and those tables contain all the data for every participant that has a string entry for any of the duplicate variables. Covid19 - 374 total; module2 - 8 total; module 3 - 58 total; module4 - 2985 total

**Comment by anthonypetersen** [comment]
@michellehudson it looks like module 4 should have more in your table?

**Comment by anthonypetersen** [comment]
Notifications error code should be fixed

**Comment by anthonypetersen** [comment]
Country of Origin should be fixed now, the notifications one can be ignored for now @hullingsag
