### ISSUE TITLE
BSWH - ConnectApp Repo

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#885]
ConnectApp repository will require an update for site Baylor Scott and White Health (BSWH) integration. Logos, HIPAA/Consent to be included here once received.

**Comment by robertsamm** [comment]
BSWH consent and HIPAA forms:
PDF consent: https://nih.app.box.com/file/1462772706015
PDF HIPAA: https://nih.app.box.com/file/1463678718293

Variables to be used for forms:
Consent: BSWH_Consent_V0.02 
HIPAA: BSWH_HIPAA_V0.01
(note, BSWH consent will start at v0.02 because that is the first that was IRB approved)

**Comment by depietrodeanna** [comment]
BSWH logo files here: https://nih.app.box.com/folder/253550673453 @sonyekere

**Comment by Gbarra9** [comment]
Notes from BSWH Site Integration (Code changes)

- Add new site to reference in shared.js file for sites and allIHCS & siteAcronyms functions 
- Forms for New Site 
	- Consent forms in HTML and PDF 
	- HIPAA forms in HTML and PDF
- My Samples Page 
	- Requires site specific text, add new site object with keys and string values Example  const nci = { concept: ‘13’, name: ‘NCI’, …}
- myToDoList.js -> myToDoList function
- images/<BSWH_logo.png>
- forms/Consent_versioning.json
pages/agreements.js

**Comment by robertsamm** [comment]
The BSWH team confirmed the spelling of how their site should be listed and their acronym. See below. Note the ‘&’ instead of ‘and’ and no commas.

•	Baylor Scott & White Health
•	BSWH

**Comment by robertsamm** [comment]
Tracked versions of BSWH consent and HIPAA forms to use for creating HTML versions below. Changes are tracked against the V0.05 Model Consent form (https://nih.app.box.com/file/1421740873254) and V0.02 Model HIPAA form (https://nih.app.box.com/file/1181276378818):

- BSWH tracked consent: https://nih.app.box.com/file/1505231637161
- BSWH tracked HIPAA: https://nih.app.box.com/file/1505232102210

**Comment by depietrodeanna** [comment]
@Gbarra9 updated logo files here: https://app.box.com/s/d5a1eg7eb3yxhrhb07nqg3eo7w1n9mr6

**Comment by robertsamm** [comment]
@Gbarra9 I found a few small issues in the HTML display of the BSWH consent form. See below. 

1.	Capitalize the 'h' in ‘Health’ in Study Site title
![image](https://github.com/episphere/connect/assets/67074735/9aad0d26-9cc2-43fa-b798-2970cb74ba98) 

2.	Missing last paragraph of Baylor specific language in ‘it is your choice to take part in the study’ section
![image](https://github.com/episphere/connect/assets/67074735/27559621-87f9-43bb-a345-e8daacb8408f)

3.	Missing last sentence of Baylor specific language in ‘what are the risks and discomforts…’ – donated specimens section
![image](https://github.com/episphere/connect/assets/67074735/fdfb708d-d1aa-4dad-95ea-916b0e460614) 

4.	Please add space/blank line between phone number and consent document to separate these out some
![image](https://github.com/episphere/connect/assets/67074735/f1fe0e3e-a367-4849-8735-506b38dadbc3)

5.	Please move ‘Name:’ down to separate line and have blank line between 'name' and 'date' (like how it is with 'date' and 'signature')
![image](https://github.com/episphere/connect/assets/67074735/887ee723-e4bc-48bc-a100-4fe8674f06e3)

HTML HIPAA form looked good.

**Comment by Gbarra9** [comment]
> @Gbarra9 I found a few small issues in the HTML display of the BSWH consent form. See below.
> 
> 1. Capitalize the 'h' in ‘Health’ in Study Site title
>    ![image](https://private-user-images.githubusercontent.com/67074735/333658919-9aad0d26-9cc2-43fa-b798-2970cb74ba98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzA3MTcsIm5iZiI6MTcxNjU3MDQxNywicGF0aCI6Ii82NzA3NDczNS8zMzM2NTg5MTktOWFhZDBkMjYtOWNjMi00M2ZhLWI3OTgtMjk3MGNiNzRiYTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2Q2NGE4MWQwODM2Y2Q3MjAyN2QyMzQ3ZjY0OGVhM2RkYTFiNDgxNTY1OGI1MmQ5MWVjMDg0MmIyNDhlN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mx9PgCdxazLX6GoVyLXcjwhOkURYqWNdDVNccbFswnM)
> 2. Missing last paragraph of Baylor specific language in ‘it is your choice to take part in the study’ section
>    ![image](https://private-user-images.githubusercontent.com/67074735/333658960-27559621-87f9-43bb-a345-e8daacb8408f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzA3MTcsIm5iZiI6MTcxNjU3MDQxNywicGF0aCI6Ii82NzA3NDczNS8zMzM2NTg5NjAtMjc1NTk2MjEtODdmOS00M2JiLWEzNDUtZThkYWFjYjg0MDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTk1YzViMTUxZTA3NTQyN2NlOTA4YWY5ZTgzNTk0MWZjMDVhMzg4YWQ0N2ZiMTMxZDFkNzEzMzAzNzc5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUuyqmXHQ3dkrKJaz2MgLDivDt1BiLP505_r6oe0140)
> 3. Missing last sentence of Baylor specific language in ‘what are the risks and discomforts…’ – donated specimens section
>    ![image](https://private-user-images.githubusercontent.com/67074735/333659004-fdfb708d-d1aa-4dad-95ea-916b0e460614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzA3MTcsIm5iZiI6MTcxNjU3MDQxNywicGF0aCI6Ii82NzA3NDczNS8zMzM2NTkwMDQtZmRmYjcwOGQtZDFhYS00ZGFkLTk1ZWEtOTE2YjBlNDYwNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzdmMjk1Mzc5ZTA1NmUxYWJkZDYwYmM3NmUyMTgwNGMyY2NmZmVkNjAyZjlhYTFkZDBmNzI5YTRhZmZkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7a_Xc-A7URg4UPl5LYiLg4jsdop1uuoNils-CtoNsM8)
> 4. Please add space/blank line between phone number and consent document to separate these out some
>    ![image](https://private-user-images.githubusercontent.com/67074735/333659053-f1fe0e3e-a367-4849-8735-506b38dadbc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzA3MTcsIm5iZiI6MTcxNjU3MDQxNywicGF0aCI6Ii82NzA3NDczNS8zMzM2NTkwNTMtZjFmZTBlM2UtYTM2Ny00ODQ5LTg3MzUtNTA2YjM4ZGFkYmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTAyNmE3YzNlOTc1MDZkNmI4YTBjOThjZjQ3NjNiODBmMTc3YTRiOWZmZjNlYWRiZDA3YWJiNWUxMWFlOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFONGDFvNvVHIFg5jgXTQ1Cd8zjYEo6Z_HRMAFR6aQY)
> 5. Please move ‘Name:’ down to separate line and have blank line between 'name' and 'date' (like how it is with 'date' and 'signature')
>    ![image](https://private-user-images.githubusercontent.com/67074735/333659096-887ee723-e4bc-48bc-a100-4fe8674f06e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzA3MTcsIm5iZiI6MTcxNjU3MDQxNywicGF0aCI6Ii82NzA3NDczNS8zMzM2NTkwOTYtODg3ZWU3MjMtZTRiYy00OGJjLWExMDAtNGZlODY3NGYwNmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYjYxMTEyMzJjMzI2MTBkOWIyNDBiN2Y5NmUyMTQxZTAwZTM5NWNlZDA1NDBhNDljMjA3OWE3YzY5ZjliMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WRrny4ni4HfuSGfaud8-MwZoW0tQz1whtayN0RA8UOA)
> 
> HTML HIPAA form looked good.

Thanks I'll make the changes.

**Comment by Gbarra9** [comment]
I am able to access the file, thanks @robertsamm.

**Comment by Gbarra9** [comment]
@robertsamm BSWH's "HTML consent form" and "My Samples" page content is updated

**Comment by depietrodeanna** [comment]
@Gbarra9 My Samples page is ready in dev for testing?

**Comment by Gbarra9** [comment]
> @Gbarra9 My Samples page is ready in dev for testing?

Yes, I fixed and updated the text content.

**Comment by depietrodeanna** [comment]
@Gbarra9 Reviewing My Samples page in dev. The heading is missing the name of BSWH as displayed on the My Samples document here https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d

<img width="861" alt="Screenshot 2024-05-30 at 9 08 11 PM" src="https://github.com/episphere/connect/assets/74061787/6702a16f-609e-4d04-a92f-139c7a1ebb32">

I've made other comments directly in the document to draw your attention. Please review and let me know when updates are in dev for re-testing. Thanks!

**Comment by cunnaneaq** [comment]
@Gbarra9 Reviewing consent HTML updates - Items # 1-3 above look good!  Very minor spacing issues remaining from 4 & 5

5 - name is on the next line, but would be great if spacing could look more like that between date and signature  

Screenshot shows both 4 and 5

![Screenshot 2024-05-31 at 1 09 16 PM](https://github.com/episphere/connect/assets/83971268/d820d448-40d2-4e30-ba20-bdb9970935da)

**Comment by Gbarra9** [comment]
> @Gbarra9 Reviewing My Samples page in dev. The heading is missing the name of BSWH as displayed on the My Samples document here https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d
> I've made other comments directly in the document to draw your attention. Please review and let me know when updates are in dev for re-testing. Thanks!

Created PR for comment:
- https://github.com/episphere/connect/issues/885#issuecomment-2141071122

Pending Team Review and will comment when changes are merged to dev.

**Comment by Gbarra9** [comment]
> @Gbarra9 Reviewing consent HTML updates - Items # 1-3 above look good! Very minor spacing issues remaining from 4 & 5
> 
> 5 - name is on the next line, but would be great if spacing could look more like that between date and signature
> 
> Screenshot shows both 4 and 5

@cunnaneaq Thanks for the feedback. I'll get started on this.

**Comment by Gbarra9** [comment]
> @Gbarra9 Reviewing My Samples page in dev. The heading is missing the name of BSWH as displayed on the My Samples document here https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d
> I've made other comments directly in the document to draw your attention. Please review and let me know when updates are in dev for re-testing. Thanks!

The changes are merged in dev and can be reviewed again.

**Comment by Gbarra9** [comment]
> > [@Gbarra9](https://github.com/Gbarra9) Reviewing consent HTML updates - Items # 1-3 above look good! Very minor spacing issues remaining from 4 & 5
> > 5 - name is on the next line, but would be great if spacing could look more like that between date and signature
> > Screenshot shows both 4 and 5
> 
> [@cunnaneaq](https://github.com/cunnaneaq) Thanks for the feedback. I'll get started on this.

The changes for 4 & 5 are merged in dev and can be retested.

**Comment by depietrodeanna** [comment]
> > @Gbarra9 Reviewing My Samples page in dev. The heading is missing the name of BSWH as displayed on the My Samples document here https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d
> > I've made other comments directly in the document to draw your attention. Please review and let me know when updates are in dev for re-testing. Thanks!
> 
> The changes are merged in dev and can be reviewed again.

Reviewed in dev. ready for stage.

**Comment by depietrodeanna** [comment]
@jhflorey @Gbarra9 Not sure who will work on this but the name of the health care system is missing in dev on the My Samples page for Baylor Scott & White Health as well as other sites I've made test accounts for in dev and found incidentally (HP and HFH). Please update to ensure the name of the health care system is on the My Samples page:

<img width="1002" alt="my samples name missing" src="https://github.com/episphere/connect/assets/74061787/c9622b1f-976c-4780-bedb-630cdad733ca">

**Comment by jhflorey** [comment]
@depietrodeanna Just updated. Please check in dev.

**Comment by depietrodeanna** [comment]
@jhflorey checked for a BSWH and HP test account in dev and this is fixed. Thanks

**Comment by depietrodeanna** [comment]
@jhflorey My Samples page in stage needs some adjustments. see my comments here and let me know you want to get on a call: https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d

**Comment by jhflorey** [comment]
@depietrodeanna Please check it in dev.

**Comment by robertsamm** [comment]
PWA looks good in stage for BSWH for internal testing. BSWH to conduct E2E testing later this week.

**Comment by depietrodeanna** [comment]
My Samples page is reviewed in stage and ready for prod
